name: werkbank
description: >-
  A powerful tool that helps you develop, test, visualize, and organize your Flutter UI components.
version: 0.15.1
repository: https://github.com/neusta-mobile-solutions-gmbh/werkbank/

environment:
  sdk: ^3.8.0
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  equatable: ^2.0.7
  intl: ^0.20.2
  go_router: ^15.1.2
  uuid: ^4.5.1
  animations: ^2.0.11
  collection: ^1.19.1
  meta: ^1.16.0
  fast_immutable_collections: ^11.0.4
  url_launcher: ^6.3.1
  graphs: ^2.3.2
  vector_math: ^2.1.4
  slang: ^4.7.2
  shared_preferences: ^2.5.3
  flutter_markdown_plus: ^1.0.3
  fuzzy: ^0.5.1
  web: ^1.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  very_good_analysis: ^8.0.0
  index_generator: ^3.4.1
  icon_font_generator: ^4.0.0
  path: ^1.9.1
  yaml: ^3.1.3
  # localizations? `fvm dart run slang`

flutter:
  uses-material-design: true

  assets:
    - assets/components/background/
  fonts:
    - family: Werkbank Icons
      fonts:
        - asset: assets/fonts/werkbank_icon_font.otf
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter_24pt-BlackItalic.ttf
          style: italic
          weight: 900
        - asset: assets/fonts/Inter_24pt-Black.ttf
          weight: 900
        - asset: assets/fonts/Inter_24pt-BoldItalic.ttf
          style: italic
          weight: 700
        - asset: assets/fonts/Inter_24pt-Bold.ttf
          weight: 700
        - asset: assets/fonts/Inter_24pt-ExtraBoldItalic.ttf
          style: italic
          weight: 800
        - asset: assets/fonts/Inter_24pt-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Inter_24pt-ExtraLightItalic.ttf
          style: italic
          weight: 200
        - asset: assets/fonts/Inter_24pt-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Inter_24pt-Italic.ttf
          style: italic
        - asset: assets/fonts/Inter_24pt-LightItalic.ttf
          style: italic
          weight: 300
        - asset: assets/fonts/Inter_24pt-Light.ttf
          weight: 300
        - asset: assets/fonts/Inter_24pt-MediumItalic.ttf
          style: italic
          weight: 500
        - asset: assets/fonts/Inter_24pt-Medium.ttf
          weight: 500
        - asset: assets/fonts/Inter_24pt-Regular.ttf
          weight: 400
        - asset: assets/fonts/Inter_24pt-SemiBoldItalic.ttf
          style: italic
          weight: 600
        - asset: assets/fonts/Inter_24pt-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Inter_24pt-ThinItalic.ttf
          style: italic
          weight: 100
        - asset: assets/fonts/Inter_24pt-Thin.ttf
          weight: 100
    - family: JetBrains Mono
      fonts:
        - asset: assets/fonts/JetBrainsMono-BoldItalic.ttf
          style: italic
          weight: 700
        - asset: assets/fonts/JetBrainsMono-Bold.ttf
          weight: 700
        - asset: assets/fonts/JetBrainsMono-ExtraBoldItalic.ttf
          style: italic
          weight: 800
        - asset: assets/fonts/JetBrainsMono-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/JetBrainsMono-ExtraLightItalic.ttf
          style: italic
          weight: 200
        - asset: assets/fonts/JetBrainsMono-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/JetBrainsMono-Italic.ttf
          style: italic
        - asset: assets/fonts/JetBrainsMono-LightItalic.ttf
          style: italic
          weight: 300
        - asset: assets/fonts/JetBrainsMono-Light.ttf
          weight: 300
        - asset: assets/fonts/JetBrainsMono-MediumItalic.ttf
          style: italic
          weight: 500
        - asset: assets/fonts/JetBrainsMono-Medium.ttf
          weight: 500
        - asset: assets/fonts/JetBrainsMono-Regular.ttf
          weight: 400
        - asset: assets/fonts/JetBrainsMono-SemiBoldItalic.ttf
          style: italic
          weight: 600
        - asset: assets/fonts/JetBrainsMono-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/JetBrainsMono-ThinItalic.ttf
          style: italic
          weight: 100
        - asset: assets/fonts/JetBrainsMono-Thin.ttf
          weight: 100
