name: werkbank_lints
description: The lints package for all Werkbank packages.
version: 1.0.0

environment:
  sdk: ^3.8.1

resolution: workspace

dependencies:
  flutter_lints: ^6.0.0

dev_dependencies:
  yaml: ^3.1.3
