name: werkbank_lints
description: The lints package for all Werkbank packages.
version: 1.0.0

environment:
  sdk: ^3.10.0

resolution: workspace

dependencies:
  flutter_lints: ^6.0.0
  analysis_server_plugin: ^0.3.3
  analyzer: ^8.0.0

dev_dependencies:
  yaml: ^3.1.3
